export type HomeLocale = "es" | "en";

export const copy = {
  es: {
    heroTitle: "Tu próxima aventura empieza aquí",
    exploreTours: "Explorar tours",
    language: "Lenguaje",
    spanish: "Español",
    english: "English",
    searchPlaceholder: "Buscar tour por nombre",
    allCategories: "Todos",
    duration: "Duración",
    priceFrom: "Desde",
    dollars: "dólares",
    exploreTour: "Explorar tour",
    categoryFallback: "Categoría",
    helpAria: "Ayuda",
    tourDetailTitle: "Detalle del tour",
    close: "Cerrar",
    backToHome: "Volver al inicio",
  },
  en: {
    heroTitle: "Your next adventure starts here",
    exploreTours: "Explore tours",
    language: "Language",
    spanish: "Spanish",
    english: "English",
    searchPlaceholder: "Search tour by name",
    allCategories: "All",
    duration: "Duration",
    priceFrom: "From",
    dollars: "USD",
    exploreTour: "Explore tour",
    categoryFallback: "Category",
    helpAria: "Help",
    tourDetailTitle: "Tour details",
    close: "Close",
    backToHome: "Back to home",
  },
} as const;
