export type HomeLocale = "es" | "en";

export const copy = {
  es: {
    heroTitle: "Tu próxima aventura empieza aquí",
    exploreTours: "Explorar tours",
    language: "Lenguaje",
    spanish: "Español",
    english: "English",
    searchPlaceholder: "Buscar tour por nombre",
    allCategories: "Todos",
    duration: "Duración",
    priceFrom: "Desde",
    dollars: "dólares",
    exploreTour: "Explorar tour",
    categoryFallback: "Categoría",
    helpAria: "Ayuda",
    tourDetailTitle: "Detalle del tour",
    close: "Cerrar",
    backToHome: "Volver al inicio",
    capacity: "Capacidad",
    persons: "personas",
    difficulty: "Dificultad",
    schedules: "Horarios",
    requirements: "Requisitos",
    bookTour: "Reservar tour",
    hours: "horas",
    backToCatalog: "Volver al catálogo",
    tourToBook: "Tour a reservar",
    fullName: "Nombre",
    fullNamePlaceholder: "Ingresar nombre completo",
    amountOfPeople: "Cantidad de personas",
    amountOfPeoplePlaceholder: "Ingrese la cantidad de personas",
    date: "Fecha",
    datePlaceholder: "Selecciona la fecha de la reserva",
    time: "Hora",
    timePlaceholder: "Seleccionar la hora de la reserva",
    timeSelectDateFirst: "Primero selecciona una fecha",
    timeNoSchedulesForDay: "No hay horarios disponibles para este día",
    requiresTransfer: "¿Requiere transfer?",
    yes: "Sí",
    no: "No",
    requestReservation: "Solicitar reserva",
    validationFullNameRequired: "El nombre es requerido",
    validationPeopleRequired: "La cantidad de personas es requerida",
    validationPeopleInvalid: "Ingrese una cantidad válida",
    validationPeopleMin: "Mínimo 1 persona",
    validationPeopleMax: "Máximo {count} personas para este tour",
    validationDateRequired: "La fecha es requerida",
    validationDatePast: "La fecha no puede ser anterior a hoy",
    validationScheduleRequired: "Seleccione una hora",
  },
  en: {
    heroTitle: "Your next adventure starts here",
    exploreTours: "Explore tours",
    language: "Language",
    spanish: "Spanish",
    english: "English",
    searchPlaceholder: "Search tour by name",
    allCategories: "All",
    duration: "Duration",
    priceFrom: "From",
    dollars: "USD",
    exploreTour: "Explore tour",
    categoryFallback: "Category",
    helpAria: "Help",
    tourDetailTitle: "Tour details",
    close: "Close",
    backToHome: "Back to home",
    capacity: "Capacity",
    persons: "persons",
    difficulty: "Difficulty",
    schedules: "Schedules",
    requirements: "Requirements",
    bookTour: "Book tour",
    hours: "hours",
    backToCatalog: "Back to catalog",
    tourToBook: "Tour to book",
    fullName: "Name",
    fullNamePlaceholder: "Enter full name",
    amountOfPeople: "Amount of people",
    amountOfPeoplePlaceholder: "Enter the amount of people",
    date: "Date",
    datePlaceholder: "Select reservation date",
    time: "Time",
    timePlaceholder: "Select reservation time",
    timeSelectDateFirst: "Select a date first",
    timeNoSchedulesForDay: "No schedules available for this day",
    requiresTransfer: "Requires transfer?",
    yes: "Yes",
    no: "No",
    requestReservation: "Request reservation",
    validationFullNameRequired: "Name is required",
    validationPeopleRequired: "The number of people is required",
    validationPeopleInvalid: "Enter a valid number of people",
    validationPeopleMin: "Minimum 1 person",
    validationPeopleMax: "Maximum {count} people for this tour",
    validationDateRequired: "Date is required",
    validationDatePast: "Date cannot be earlier than today",
    validationScheduleRequired: "Select a time",
  },
} as const;
